### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by wldcordeiro** [abe33/minimap-pigments#2]
[Enter steps to reproduce below:]
1. Close a file where minimap-pigments were present

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [minimap-pigments](https://github.com/abe33/minimap-pigments) package, v0.1.6
### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /home/wldcordeiro/.atom/packages/minimap-pigments/lib/minimap-pigments-binding.coffee:44

TypeError: Cannot read property 'destroy' of undefined
  at MinimapPigmentsBinding.module.exports.MinimapPigmentsBinding.destroyDecorations (/home/wldcordeiro/.atom/packages/minimap-pigments/lib/minimap-pigments-binding.coffee:44:15)
  at MinimapPigmentsBinding.module.exports.MinimapPigmentsBinding.destroy (/home/wldcordeiro/.atom/packages/minimap-pigments/lib/minimap-pigments-binding.coffee:39:6)
  at /home/wldcordeiro/.atom/packages/minimap-pigments/lib/minimap-pigments.coffee:46:17
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:290:27)
  at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:468:18)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -2:29.2.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:20.9.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -2:16.2.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:49.3.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 14x -1:41.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:39.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:39.5.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:39 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:39 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 15x -1:37.2.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:12.7.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:09.9.0 command-palette:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 markdown-preview:toggle (atom-text-editor.editor.vim-mode.insert-mode)
     -0:04.1.0 zen:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:04.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-light.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-light"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      "__pycache__",
      ".svn",
      ".DS_Store",
      "Thumbs.db"
    ],
    "projectHome": "/home/wldcordeiro/Documents"
  }
}
```
### Installed Packages

``` coffee
# User
Zen, v0.16.2
atom-handlebars, v1.2.0
atom-jinja2, v0.5.0
atom-material-syntax-light, v0.0.3
atom-material-ui, v0.6.2
atom-ternjs, v0.8.1
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
autocomplete-ruby, v0.1.0
bezier-curve-editor, v0.7.2
bottom-dock, v0.3.5
caniuse, v0.5.5
circle-ci, v0.10.1
clipboard-plus, v0.5.1
color-picker, v2.0.12
django-templates, v0.5.0
editorconfig, v1.2.0
emmet, v2.3.13
file-icons, v1.6.9
git-log, v0.4.1
language-django, v0.1.1
language-javascript-jsx, v0.3.7
language-restructuredtext, v0.9.0
language-rust, v0.4.5
linter, v1.8.0
linter-eslint, v3.1.0
linter-flake8, v1.7.0
linter-manager, v0.2.3
linter-rust, v0.2.9
linter-scss-lint, v2.2.1
minimap, v4.13.4
minimap-autohide, v0.10.1
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.1
omni-ruler, v0.4.2
pain-split, v1.4.0
pigments, v0.15.0
project-manager, v2.6.1
racer, v0.17.2
regex-railroad-diagram, v0.10.3
set-syntax, v0.3.0
sync-settings, v0.6.0
theme-toggler, v0.4.0
vim-mode, v0.60.0
vim-mode-clipboard-plus, v0.1.0
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @wldcordeiro, thanks for the report, I just released a patch with a guard against that error.
